website/music/urls.py
from django.conf.urls import url
from . import views
app_name = 'music'
urlpatterns = [
# /music/
    url(r'^$', views.index, name='index'),
# /music/81/
url(r'^(?P<album_id>[0-9]+)/$',views.details,name="details"),
# /music/81/favourite
url(r'^(?P<album_id>[0-9]+)/faviroute/$',views.faviroute,name="faviroute"),
]

website/website/urls.py
from django.conf.urls import  include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
   	url(r'^music/', include('music.urls'))
]

website/music/models.py
from django.db import models

class Album(models.Model):
	artist = models.CharField(max_length=250)
	album_title = models.CharField(max_length=500)
	gener = models.CharField(max_length=500)
	album_logo = models.CharField(max_length=1000)

	def __str__(self):
		return self.artist+'-'+self.album_title


class Songs(models.Model):
	album = models.ForeignKey(Album,on_delete=models.CASCADE)
	file_type = models.CharField(max_length=500)
	song_title = models.CharField(max_length=500)
	is_faviroute = models.BooleanField(default=False)

	def __str__(self):
		return self.song_title

website/music/views.py
from django.shortcuts import render,get_object_or_404
from  django.shortcuts import render
from  .models import Album

#  music index page function
def index(request):
	all_albums = Album.objects.all()
	return render(request, 'music/index.html', {'all_albums': all_albums})

# details about album function
def details(request,album_id):
	# try:
	# 	album = Album.objects.get(pk=album_id)
	# except:
	# 	raise Http404("Album Doesnot Exist")
	#  instead of writing 404 again and again use builtin get_objecct_or_404 

	album = get_object_or_404(Album,pk=album_id)
	return render(request, 'music/details.html', {'album':album})


def faviroute(request,album_id):
	album = get_object_or_404(Album,pk=album_id)
	try:
		selected_song = album.songs_set.get(pk=request.POST['song'])
	except(KeyError):
		return render(request, 'music/details.html', {'album':album, 'error_message':'Select Some Thing'})
	else:
		selected_song.is_faviroute = True
		selected_song.save()
		return render(request, 'music/details.html', {'album':album})

website/music/templates/music/details.html
{% extends 'music/navbar.html'%}
{% block title %} Songs Details {% endblock%}
{% block body %}

	<img src="{{album.album_logo}}">
	<h2> {{album.album_title}} </h2>
	<h2> {{album.artist}} </h2>
	{% if error_message %}
	<p><strong>{{error_message}}</strong></p>
	{% endif %}
	<form action="{% url 'music:faviroute' album.id %}" method="post">
	{%csrf_token%}
	{% for song in album.songs_set.all %}
	{{songs.id}}
		<input type="radio" id="song{{forloop.counter}}" name="song" value="{{songs.id}}"/>
		<label for="song{{forloop.counter}}">
			{{song.song_title}}
			{% if song.is_faviroute %}
				<img src="https://s3.amazonaws.com/ionic-marketplace/ionicratings/screenshot_1.png">
			{% endif %}
		</label><br>

	{% endfor %}
		
	<input type="submit" value="faviroute">
	</form>

{% endblock %}

website/music/templates/music/index.html
{% extends 'music/navbar.html' %}
{% block title %} Albums {% endblock%}
{% block body %}
	{% if all_albums %}
		<h2>Here is Album list</h2>
		<ul>
			{% for album in all_albums %}
			<li><a href="{% url 'music:details' album.id %}"> {{album.album_title}}</li>
			{% endfor %}

		</ul>
	{% else %}
	<h2> You don't have any albums</h2>
	{% endif %}

{% endblock %}

website/music/templates/music/navbar.html
<!DOCTYPE html>
<html>
<head>
	<title>{% block  title %} Dakr {% endblock %}</title>
		{% load staticfiles%}
<link rel="stylesheet" type="text/css" href="{% static 'music/style.css'%}">
<link href='https://fonts.googleapis.com/css?family=Satisfy' rel='stylesheet' type='text/css'>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>


</head>
<body>
<nav class="navbar navbar-inverse">
	<div class="container-fluid">
		<div class="navbar-header">
		<button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#topNavBar">
			<span class="icon-bar"></span>
			<span class="icon-bar"></span>
			<span class="icon-bar"></span>
		</button>
			<a class="navbar-brand" href="{% url 'music:index'%}">Dakr</a>

		</div>

		<!-- itemss -->
		<div class="collapse navbar-collapse" id="topNavBar">
		<ul class="nav navbar-nav">
			<li class="active">
			<a href="{% url 'music:index'%}">
				<span class="glyphicon glyphicon-cd" area-hidden="true"></span>&nbsp; Album
			</a>
				
			</li>
			<li class="">
			<a href="#">
				<span class="glyphicon glyphicon-music" area-hidden="true"></span>&nbsp; Song
			</a>
				
			</li>

		</ul>
		<form class="navbar-form navbar-left" role="search" method="get" action="#">
			<div class="form-group">
			<input type="text"  class="form-control" name="q" value="">
			</div>
			<button type="submit" class="btn btn-default">Search</button>

		</form>			
		<ul class="nav navbar-nav navbar-right">
			<li class="">
				<a href="#">
					<span class="glyphicon glyphicon-plus" area-hidden="true"></span>&nbsp; Add Album
				</a>				
			</li>
			<li class="">
				<a href="#">
					<span class="glyphicon glyphicon-off" area-hidden="true"></span>&nbsp; Logout
				</a>				
			</li>

		</ul>


		</div>

	</div>
</nav>
{% block body%}
{%endblock%}
</body>
</html>